domain: package
language: prediction
project_slug: root-tissue-seg-package
project_slug_no_hyphen: root-tissue-seg-package
template_version: 'None # <<MLF-CORE_NO_BUMP>>'
template_handle: package-prediction
github_username: waseju
creator_github_username: waseju
is_github_repo: true
is_repo_private: true
is_github_orga: false
full_name: Julian Wanner
email: jwgithub@mailbox.org
project_name: root-tissue-seg-package
project_short_description: An mlf-core prediction package for root tissue segmentation.
version: 1.0.5
license: MIT
framework: pytorch
